config/routes.rb
Cognito1::Application.routes.draw do

  resources :timezones

  match "/tagsearch_results/" => "events#tagsearch_results", :via => :get, :as =>"tagsearch_results"
  match "popular/events", :to => "events#popularevents"
  match "popular/tags", :to => "events#popular_tags"
  match "popular/users", :to => "events#popular_users"
  
  get "events/tagsearch" => "events#tagsearch", :as => :tagsearch

  get "events/tags" => "events#tags", :as => :tags

  match "events/hosting", :to => 'events#hosting'
  match "events/watching", :to => 'events#watching'
  match "events/attending", :to => 'events#attending'
  resources :events

  
  resources :attendees
  
  match "attendees/add_vote", :to => 'attendees#add_vote'
  match "attendees/remove_vote", :to => 'attendees#remove_vote'
  
  resources :watchers
  
  resources :resources
  
  resources :events do
    member do
      get :resources
    end  
  end
  
  
  

  
  get "relationships/create"

  get "relationships/destroy"

  resources :users do
    member do
      get :following, :followers
    end  
  end
  
  
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/popular', :to => 'pages#popular'
  match '/test', :to => 'pages#test'
  
  
  root :to => 'pages#home'

end

app/models/event.rb
# == Schema Information
#
# Table name: event_sessions
#
#  id               :integer         not null, primary key
#  user_host_id     :integer
#  channel_id       :integer
#  difficulty_id    :integer
#  status_id        :integer
#  timezone_id      :integer
#  size_id          :integer
#  title            :string(255)
#  content          :string(255)
#  session_datetime :datetime
#  duration         :integer
#  prereqs          :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#


class Event < ActiveRecord::Base

  has_one :channel
  has_one :difficulty
  has_one :size
  has_one :status
  has_one :timezone
  
  has_many :attendees
  has_many :users, :through => :attendees
  
  has_many :watchers
  has_many :users, :through => :watchers
  
  has_many :resources
  
  #has_many :tags
  #has_many :tags, :through => :event_tags
  
  accepts_nested_attributes_for :resources
  
  acts_as_taggable_on :tags
  
  acts_as_voteable
  

  attr_accessible :tag_list, :event_tokens, :user_host_id, :channel_id, :difficulty_id, :status_id, :timezone_id, :size_id, :title, :content, :session_datetime, :duration, :prereqs
  attr_accessible :resources_attributes
  attr_reader :event_tokens

  class << self
    def check_owner(host, user)
      host == user ? true : false
    end
  end
  
  def event_tokens=(ids)
       ids.gsub!(/CREATE_(.+?)_END/) do
         Tag.create!(:name => $1).id
       end

     end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate
  helper_method :sort_column, :sort_direction

  def tags 
      @tags = ActsAsTaggableOn::Tag.where("tags.name LIKE ?", "%#{params[:q]}%") 
      respond_to do |format|
        format.json { render :json => @tags.map{|t| {:id => t.name, :name => t.name }}}
      end
  end
  
  def index
    require 'will_paginate/array'
    @title = "All Events"
    @user = User.find(current_user.id)
    @search = Event.search(params[:search])
    @search_sort = @search.order(sort_column + ' ' + sort_direction)
    @events = @search_sort.paginate(:page => params[:page], :per_page => 10)
    
  end
  
  def tagsearch
    require 'will_paginate/array'
    @title = "Tag Searched Events"
    @search = Event.tagged_with(params[:tags])
    @events = @search.paginate(:page => params[:page], :per_page => 10)
  end
  
  def vote_check(ev_id)
    @user = User.find(current_user.id)
    @event = Event.find(ev_id)
    @user.voted_for? @event
  end
  
  def show
    @events             = Event.find(params[:id])
    #@eventresources     = EventResource.find_by_event_id(params[:id])
    #@resources          = Resource.find(@eventresources.resource_id)
  end
  
  def create
    #Need to pick up the current user for the user_host_id
    @event = Event.new(params[:event])
    @event.user_host_id = current_user.id
    #@event = current_user.event.build(params[:event])
    if @event.save
      redirect_to @event, :flash => { :success => "Event Created! "}
    else    
      @title = "Something's Wrong"
      render 'index'
    end
  end
  
  def new
    @title = "Create Event"
    @event = Event.new
    @channels           = Channel.find(:all, :order => "id")
    @difficulties       = Difficulty.find(:all, :order => "id")
    @sizes              = Size.find(:all, :order => "id")
    @statuses           = Status.find(:all, :order => "id")
    @timezones          = Timezone.find(:all, :order => "id")
  end
  
  def edit
    @title = "Edit User"
    @event = Event.find(params[:id])
    @channels           = Channel.find(:all, :order => "id")
    @difficulties       = Difficulty.find(:all, :order => "id")
    @sizes              = Size.find(:all, :order => "id")
    @statuses           = Status.find(:all, :order => "id")
    @timezones          = Timezone.find(:all, :order => "id")
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event, :flash => { :success => "Event Updated"}
    else
      
      @title = "Edit Event"
      render 'edit'  
    end
  end
  
  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path, :flash => { :error => "Event Destroyed."}
  end

  def resources
    @resources = Event.find(params[:id]).resources
    render 'resources/show' 
  end
  
  def hosting
    require 'will_paginate/array'
    @title = "Hosting"
    @event = Event.find_all_by_user_host_id(current_user.id)
    @events = @event.paginate(:page => params[:page], :per_page => 10)
    render 'event_hosting'
  end
  
  def watching
    require 'will_paginate/array'
    @title = "Watching"
    conditions = ['watchers.user_id = ?', current_user.id]
    @event = Event.joins(:watchers).find(:all, :conditions => conditions)
    @events = @event.paginate(:page => params[:page], :per_page => 10)
    render 'event_watching'
  end
  
  def attending
    require 'will_paginate/array'
    @title = "Attending"
    conditions = ['attendees.user_id = ?', current_user.id]
    @event = Event.joins(:attendees).find(:all, :conditions => conditions)
    @events = @event.paginate(:page => params[:page], :per_page => 10)
    render 'event_attending'
  end
    
  def popularevents
    @title = "Popular Events"
    @top_events = Vote.find(:all,
                            :select => 'events.id, events.title, count(votes.id) as vote_count',
                            :joins  => 'INNER JOIN events on votes.voteable_id = events.id',
                            :group  => 'events.id, events.title',
                            :limit  => 10,
                            :order  => 'count(votes.id) DESC',
                            :conditions => ["vote = ?", true])
  end
  
  def popular_tags
    @title = "Popular Tags"
    # SQLite version
    #@top_tags =   Tag.find( :all,
    #                        :select => 'tags.name, count(tags.id) as tag_count',
    #                        :joins  => 'INNER JOIN taggings on tags.id = taggings.tag_id, events on taggings.taggable_id = events.id',
    #                        :group  => 'tags.name',
    #                        :limit  => 10,
    #                        :order  => 'count(tags.id) DESC')
    # Postgres version
    @top_tags =   Tag.find( :all,
                            :select => 'tags.name, count(tags.id) as tag_count',
                            :joins  => ',taggings, events',
                            :group  => 'tags.name',
                            :limit  => 10,
                            :order  =>'count(tags.id) DESC', 
                            :conditions => 'tags.id=taggings.tag_id and taggings.taggable_id = events.id')
                            
  end
  
  def popular_users
    @title = "Popular Users"

    @top_users = Event.find(:all,
                            :select => 'user_host_id, count(votes.id) as vote_count',
                            :joins  => 'INNER JOIN votes on events.id = votes.voteable_id',
                            :group  => 'user_host_id',
                            :limit  => 10,
                            :order  => 'count(votes.id) DESC',
                            :conditions => ["vote = ?", true])

                            
  end
  
  def tagsearch_results
    require 'will_paginate/array'
    #@search = Event.metasearch({:title_or_content_or_tag_taggings_tag_name_contains => params[:search]})
   
    case ActiveRecord::Base.connection.adapter_name
    when 'SQLite'
      @search = Event.find_by_sql(["SELECT events.* from events 
                                    WHERE  
                                      (events.title LIKE ? 
                                       OR events.content LIKE ?)
                                    UNION
                                    SELECT events.* from events 
                                    INNER JOIN taggings on events.id= taggings.taggable_id
                                    INNER JOIN tags ON taggings.tag_id = tags.id 
                                    WHERE taggings.taggable_type = 'Event' 
                                     and tags.name LIKE ?", 
                                    "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%"])
    when 'PostgreSQL'
      @search = Event.find_by_sql(["SELECT events.* from events 
                                    WHERE  
                                      (events.title ILIKE ? 
                                       OR events.content ILIKE ?)
                                    UNION
                                    SELECT events.* from events 
                                    INNER JOIN taggings on events.id= taggings.taggable_id
                                    INNER JOIN tags ON taggings.tag_id = tags.id 
                                    WHERE taggings.taggable_type = 'Event' 
                                     and tags.name ILIKE ?", 
                                    "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%"])
    else
      raise 'Migration not implemented for this DB adapter'
    end
    
                                  
    @events = @search.paginate(:page => params[:page], :per_page => 10)
    render 'index'
    
  end
  
  private
  def sort_column
    params[:sort] || "created_at"
  end
  
  def sort_direction
    params[:direction] || "desc"
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
  
  def conditional_delete_button(event_id)
    
    @event = Event.find(event_id)
    
    button_to 'Delete', {  		:controller => :events,
  										        :action 	=> "destroy", 
  										        :id => @event.id},
  										      :confirm	=> 'Really destroy this event?',
  										      :method 	=> :delete
  end
  
  def conditional_edit_link(event_id)
    
    @event = Event.find(event_id)
    
    link_to "Edit", edit_event_path(@event.id) 
    
  end
  
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/events/_event.html.erb
<tr>
	  <% if(Attendee.count(:conditions => ["event_id = ? and user_id = ?", event.id, current_user.id]) >= 1) %>
	
	    <% @user = User.find(current_user.id) %>
	
	    <% @ev   = Event.find(event.id) %>
	
	    <% if(@user.voted_for? @ev ) %>
	
	      <td>
	        <%= button_to "Remove Vote", { 	            :controller => :attendees, 
														:action => "remove_vote", :id => event.id } %>
		  </td>
		
	    <% else %>
	  	  
	      <td>
	        <%= button_to "+1", { 	            :controller => :attendees, 
													:action => "add_vote", :id => event.id } %>
		  </td>
		
	    <% end %>
	
	  <% else %>
	
	  <td></td>
		
	  <% end %>
	
	<td>
	  <%= event.created_at.strftime('%d/%m/%Y %H:%M (%Z)') %>
	</td>
	<td>
	  <%= link_to event.title, event_path(:id => event.id) %>
	</td>
	
	<td>
	  <% if event.content.blank? %>
	    --
	  <% else %>
	    <%= event.content %>
	  <% end %>
	</td>
	
	<td>
	  <% if event.session_datetime.blank? %>
	    N/A
	  <% else %>
	    <%= event.session_datetime.strftime('%d/%m/%Y %H:%M (%Z)') %>
	  <% end %>
	</td>
	
	<td>  
	  <%= event.duration %> mins.
	</td>
	
	<td>
	  <%  if event.status_id.blank? %>
	    N/A
	  <% else %>
	    <% @status = Status.find(event.status_id) %>
	    <%= @status.status_name %>
	  <% end %>
	</td>
	
	<td>
	  <%  if event.timezone_id.blank? %>
	    N/A
	  <% else %>
	    <% @tz = Timezone.find(event.timezone_id) %>
	    <%= @tz.timezone_name %>
	  <% end %>
	</td>


	<td>
	  <%  if event.channel_id.blank? %>
	    N/A
	  <% else %>
	    <% @ch = Channel.find(event.channel_id) %>
	    <%= @ch.channel_name %>
	  <% end %>
	</td>
	
	<td>
	  <%  if event.size_id.blank? %>
	    N/A
	  <% else %>
	    <% @sz = Size.find(event.size_id) %>
	    <%= @sz.size_name %>
	  <% end %>
	</td>

</tr>

app/views/events/_eventlist_header.html.erb
<table class = "pretty" summary="Table Showing Basic Event Details">
		<th><b>Dig it!</b></th>
		<th><b><%= sortable "created_at", "Created Date"%></b></th>
		<th><b><%= sortable "title" %></b></th>
		<th><b><%= sortable "content" %> </b></th>
		<th><b><%= sortable "session_datetime", "Date/Time" %></b></th>
		<th><b><%= sortable "duration", "Duration/Mins" %><b></th>
		<th><b>Status</b></th>
		<th><b>Region</b></th>
		<th><b>Channel</b></th>
		<th><b>Size</b></th>

</tr>

app/views/events/edit.html.erb
<div id="wrapper">
	<ul class="tabsNJ">
		<li><a href="#" class="defaulttab" rel="tabs1">Core Event Details</a></li>
		<li><a href="#" rel="tabs2">Event Content</a></li>
	    <li><a href="#" rel="tabs3">Event Properties</a></li>
		<li><a href="#" rel="tabs4">Event Misc</a></li>
		<li><a href="#" rel="tabs5">Resources</a></li>
	</ul>
	<br/>

    <%= nested_form_for(@event) do |e| %>
    <div class="tab-content" id="tabs1">

		<%= e.label :title, "Title" %> : <%= e.text_field(:title) %></td>	
	    </tr>
	    <tr>
	      <td><%= e.label :title, "Event Date" %> :<%= e.text_field(:session_datetime, :class => "datepicker") %></td>	
	    </tr>


	    <tr><%= e.text_area :duration, :id => "dbDuration", :hidden => :true %>
	      <td>
		    <fieldset>
			  <%= e.label :duration, "Event Duration (mins)" %> :
			  <input type="text" id="duration" style="border: 0; color: #f6931f; font-weight: bold;"  name="event[duration]"/>
			  <div id="slider" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" name="event[duration]">
				<a style="left: 0%;" class="ui-slider-handle ui-state-default ui-corner-all" href="#"></a>
			  </div>
		    </fieldset>
		  </td>
	   </tr>
	
		<div class="actions">
	      <%= e.submit "Update Event" %>
	    </div>
	
	  </div>
	
	<div class="tab-content" id="tabs2">

	  <tr>
	    <div id="accordion">
	  	  <h3><a href="#">Add your Content Here!</a></h3>
		  <div>
		    <td><%= e.label :title, "Content" %> : <%= e.text_area(:content, :cols => "30", :rows => "10") %></td>	
		  </div>
	    </div>
      </tr>

	</div>
	
	<div class="tab-content" id="tabs3">
		<tr>
		    <td>
			  <fieldset>
				  <%= e.collection_select(:channel_id, @channels, :id, :channel_name, options ={:prompt => "-Select a channel"}) %>
				  <%= e.collection_select(:difficulty_id, @difficulties, :id, :difficulty_name, options ={:prompt => "-Select a Difficulty"}) %>
				  <%= e.collection_select(:size_id, @sizes, :id, :size_name, options ={:prompt => "-Select a Size"}) %>
				  <%= e.collection_select(:status_id, @statuses, :id, :status_name, options ={:prompt => "-Select a Status"}) %>
				  <%= e.collection_select(:timezone_id, @timezones, :id, :timezone_name, options ={:prompt => "-Select a Timezone"}) %>
			 </fieldset>
			<%= e.label :tag_list, "Event Tags" %><br />
			<%= e.text_field :tag_list,
			                 :id => "event_tags",
			                 "data-pre" => @event.tags.map(&:attributes).to_json %>
			</td>
		</tr>
	</div>
	
	<div class="tab-content" id="tabs4">
		 <tr>
			  <div id="accordion2">
			  	<h3><a href="#">Any Pre-Requisites?</a></h3>
				<div>
				  <td><%= e.label :title, "Pre Reqs" %> : <%= e.text_area(:prereqs, :cols => "30", :rows => "10") %></td>	
				</div>
			  </div>
		    </tr>
	</div>


	<div class="tab-content" id="tabs5">
		 <tr>
			 <%= e.fields_for :resources do |resource_form| %>
			  <%= resource_form.label "URL: " %>
			  <%= resource_form.text_field :resource_url %>
			  <%= resource_form.label "Description: " %>
			  <%= resource_form.text_field :resource_description %>
			  <%= resource_form.label "External Resource?: " %>
			  <%= resource_form.text_field :ext_int_indicator %>
			  <%= resource_form.link_to_remove "Remove" %>
			<% end %>
			<p><%= e.link_to_add "Add a resource", :resources %></p>
		 </tr>
	</div>
	
	<% end %>
	
	
</div>

app/views/events/event_attending.html.erb
<h1>Events I'm Attending</h1>
<%= link_to "Create Event!", new_event_path %>

<%= will_paginate(@events)%>
<ul class = "users">
	<table summary="Index listing of events">
	<%= render @events %>
	</table>
</ul>

app/views/events/event_hosting.html.erb
<h1>Events I'm Hosting</h1>
<%= link_to "Create Event!", new_event_path %>

<%= will_paginate(@events)%>
<ul class = "users">
	<table summary="Index listing of events">
	<%= render @events %>
	</table>
</ul>

app/views/events/event_watching.html.erb
<h1>Events I'm Watching</h1>
<%= link_to "Create Event!", new_event_path %>

<%= will_paginate(@events)%>
<ul class = "users">
	<table summary="Index listing of events being watched">
	<%= render @events %>
	</table>
</ul>

app/views/events/index.html.erb
<h1>All Events</h1>
<%= link_to "Create Event!", new_event_path %>

<br/>
<%= form_tag("/tagsearch_results", :method => "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<%= will_paginate %> 
<%= render 'eventlist_header' %>
<%= render @events %>
</table>

app/views/events/popular_tags.html.erb
<h1>What's the Buzz, Cognito?</h1>
<p><%= link_to "Top 10 Most Popular Events", popular_path %></p><p>    <%= link_to "Top 10 Most Popular Tags", "/popular/tags" %></p>
<ul class = "users">
	<table summary="Index listing Top 10 Popular Tags by Frequency">
	<tr>
	  <td>Tag</td>
	  <td># Mentions</td>
	</tr>
	<%= render @top_tags %>
	</table>
</ul>

app/views/events/popular_users.html.erb
<h1>What's the Buzz, Cognito?</h1>
<p><%= link_to "Top 10 Most Popular Events", popular_path %></p><p>    <%= link_to "Top 10 Most Popular Tags", "/popular/tags" %></p>
<ul class = "users">
	<table summary="Index listing Top 10 Popular Users by Votes">
	<tr>
	  <td>User Name</td>
	  <td># Votes</td>
	</tr>
	<tr>
	<%= render :partial => 'shared/top_users', :locals => { :user_host_id => @top_users.user_host_id } %>
	</tr>
	</table>
</ul>

app/views/events/popularevents.html.erb
<h1>What's the Buzz, Cognito?</h1>
<p><%= link_to "Top 10 Most Popular Events", popular_path %></p>
<p>    <%= link_to "Top 10 Most Popular Tags", "/popular/tags" %></p>
<ul class = "users">
	<table summary="Index listing Top 10 Popular Events by Votes">
	<tr>
	  <td>Title</td>
	  <td># Votes</td>
	</tr>
	<%= render @top_events %>
	</table>
</ul>

app/views/events/show.html.erb
<div id="wrapper">
	<ul class="tabsNJ">
		<li><a href="#" class="defaulttab" rel="tabs1">Core Event Details</a></li>
		<li><a href="#" rel="tabs2">Event Content</a></li>
	    <li><a href="#" rel="tabs3">Event Properties</a></li>
		<li><a href="#" rel="tabs4">Event Misc</a></li>
		<li><a href="#" rel="tabs5">Attend/Watch</a></li>
		<li><a href="#" rel="tabs6">Resources</a></li>

		<% if @events.user_host_id == current_user.id %><li><a href="#" rel="tabs9">Event Admin</a></li><% end %>
		
	</ul>
	<br/>


    <div class="tab-content" id="tabs1">

		<tr>
	      <td><%= label :title, "Title" %> : <%= @events.title %></td>	
	    </tr><br/>
	    <tr>
	      <td><%= label :title, "Event Date" %> :<%= @events.session_datetime %></td>	
	    </tr><br/>


	    <tr>
	      <td><%= label :duration, "Event Duration (mins)" %> :<%= @events.duration %></td>
	    </tr><br/>

	  </div>
	
	<div class="tab-content" id="tabs2">

	  <tr>

		  <div>
		    <td><%= label :title, "Content" %> : <%= @events.content %></td>	
		  </div>

      </tr>

	</div>
	
	<div class="tab-content" id="tabs3">
			  <tr>
				  <fieldset>
					<td>
					  <%  if @events.status_id.blank? %>
					    <b>Status :</b> N/A
					  <% else %>
					    <% @status = Status.find(@events.status_id) %>
					    <b>Status :</b> <%= @status.status_name %>
					  <% end %>
					</td><br/>
					<td>
					  <%  if @events.timezone_id.blank? %>
					    <b>Timezone :</b> N/A
					  <% else %>
					    <% @tz = Timezone.find(@events.timezone_id) %>
					    <b>Timezone :</b> <%= @tz.timezone_name %>
					  <% end %>
					</td><br/>
					<td>
					  <%  if @events.channel_id.blank? %>
					    <b>Channel :</b> N/A
					  <% else %>
					    <% @ch = Channel.find(@events.channel_id) %>
					    <b>Channel :</b> <%= @ch.channel_name %>
					  <% end %>
					</td><br/>
					<td>
					  <%  if @events.size_id.blank? %>
					    <b>Size :</b> N/A
					  <% else %>
					    <% @sz = Size.find(@events.size_id) %>
					    <b>Size :</b> <%= @sz.size_name %>
					  <% end %>
					</td><br/>
					<td>
					  <%  if @events.difficulty_id.blank? %>
					    <b>Difficulty :</b> N/A
					  <% else %>
					    <% @dif = Difficulty.find(@events.difficulty_id) %>
					    <b>Difficulty :</b> <%= @dif.difficulty_name %>
					  <% end %>
					</td><br/>
					</fieldset>
			</tr>	
	</div>
	
	<div class="tab-content" id="tabs4">
		<tr>
			<div>
			  <td><%= label :title, "Pre Reqs" %> : <%= @events.prereqs %></td>	
			</div>

	    </tr>
	</div>
	
	<div class="tab-content" id="tabs5">
		<table>
		 <tr>
			<td>
				<b>Attendees:</b>
				<ul>
		  			<% @events.attendees.each do |att| %>
		    	  	  <li><%= User.find(att.user_id).name %></li>
		  			<% end %>
				</ul>
			</td>
			<td>
			  <b>Watchers:</b>
			  <ul>
			    <% @events.watchers.each do |wat| %>
			      <li><%= User.find(wat.user_id).name %></li>
			    <% end %>
			  </ul>
			</td>
		</tr>
		
		</table>
		
			
				<% attendee = Attendee.find(:first, :conditions => ["event_id = ? and user_id = ?", @events.id, current_user.id])%>
				  <% if(@events.user_host_id != current_user.id) %>
				    <% # don't show attendance button if you're the host %>

				    <% if(Attendee.count(:conditions => ["event_id = ? and user_id = ?", @events.id, current_user.id]) < 1) %>
				    
				      <%= button_to 'Attend', attendees_path(:id => @events.id) %>
				    

				    <% else %>
				      
				        <%= button_to "Remove Attendance", { 	:controller => :attendees, 
																:action => "destroy", :id => @events.id },
						          						 		:confirm => "Stop Attending?", 
																:method => :delete %>
			 		  

				    <% end %>
				   <% end %>
			
			
				  <% watcher = Watcher.find(:first, :conditions => ["event_id = ? and user_id = ?", @events.id, current_user.id])%>

				  <% if(Watcher.count(:conditions => ["event_id = ? and user_id = ?", @events.id, current_user.id]) < 1) %>

				   
				      <%= button_to 'Watch', watchers_path(:id => @events.id) %>
				   

				  <% else %>

				    
				      <%= button_to "Remove Watch", { 		:controller => :watchers, 
															:action => "destroy", :id => @events.id },
						          							:confirm => "Remove Event Watch?", 
															:method => :delete %>
			 		

				  <% end %>
		

		
	</div>
	
	<div class="tab-content" id="tabs6">
		<ul>
		  <% @events.resources.each do |res| %>
		    <li><%= link_to(res.resource_description, res.resource_url) %> - <%= res.ext_int_indicator %></li>
		  <% end %>
		</ul>
	</div>
	

	
	<div class="tab-content" id="tabs9">
		 <p>Admin screen for your event</p><br/>
		<tr>
			<td>
			  <% if @events.user_host_id == current_user.id %>
			    Click this button to delete this event: <%= conditional_delete_button(@events.id) %>
			  <% end %>
			</td>

			<td>
			  <% if @events.user_host_id == current_user.id %>
			    Click this link to edit this event: <%= conditional_edit_link(@events.id) %>
			  <% end %>
			</td>
	</div>
	

	
</div>

app/views/events/tagsearch.html.erb
<h1>Search Results</h1>
<%= link_to "Create Event!", new_event_path %>
<p>
	
</p>

<%= will_paginate %> 
<ul class = "users">
	<table summary="Index listing of events">
	<%= render @events %>
	</table>
</ul>
<%= will_paginate %> 